### ISSUE TITLE
Installing CI If Not Available (Travis, AppVeyor, Azure Pipelines ...)

### ISSUE THREAD

**Issue by Nikola25** [BME-MIT-IET/IET-BARN-iet-2019#1]
I tried to authorize the AppVeyor and when I added the repository, got this error:
There was an error while trying to complate the current operation. Please contact AppVeyor support.

**Comment by Nikola25** [comment]
Uploading` a new file to install Travis: .travis.yml

(https://github.com/BME-MIT-IET/IET-BARN-iet-2019/commit/552985a5c1e0fe9a10379d1fd2c0005417999a4b)

**Comment by Nikola25** [comment]
Update .travis.yml from Java to C#

https://github.com/BME-MIT-IET/IET-BARN-iet-2019/commit/8a6d1eaf62668b6e6dd4c831de70394a17cd10fe

**Comment by hareka777** [comment]
Trying to analyze the project with Appveyor, but it asks for permission from BME MIT.

**Comment by Nikola25** [comment]
I tried to install the travist, I have got error message. 
CSC : error CS0006: Metadata file '/mscorlib.dll' could not be found [/home/travis/build/BME-MIT-IET/IET-BARN-iet-2019/Libraries/dotNetRDF/dotNetRDF.csproj]

**Comment by hareka777** [comment]
I have tried to build the project on BitBucket Pipelines, but I received an error:

The reference assemblies for framework ".NETFramework,Version=v4.0" were not found.

![image](https://user-images.githubusercontent.com/37445999/57098148-b46a8300-6d19-11e9-810e-2b01f6c29183.png)

**Comment by Nikola25** [comment]
We couldn't find a solution.
