### ISSUE TITLE
Running Codacy and related Pull Requests

### ISSUE THREAD

**Issue by hareka777** [BME-MIT-IET/IET-BARN-iet-2019#2]
Running Codacy and fixing the bugs.

**Comment by Nikola25** [comment]
Add curly braces around the nested statement(s) in this 'if' block.

**Comment by hareka777** [comment]
Removing commented out code.

**Comment by hareka777** [comment]
Fix: **Making variables readonly.**
Location: Libraries/dotNetRDF/Core/MimeTypeDefinition.cs Lines: 43, 45, 46, 49
Reason: Consistency and safety.
Assignee: Réka
Reviewer: Nikola

**Comment by hareka777** [comment]
Fix: **Make field 'private' and encapsulate it in a 'public' property.**
Location: Libraries/dotNetRDF/Query/Expressions/XPathFunctionFactory.cs
Reason: Public fields in public classes do not respect the encapsulation principle and can be modified from anywhere.
Assignee: Réka
Reviewer: Nikola
Pull Request:

**Comment by Nikola25** [comment]
Change this constant to a 'static' read-only property.
Location: Libraries/dotNetRDF/Query/Expressions/LeviathanFunctionFactory.cs
Release: Constant members are copied at compile time to the call sites, instead of being fetched at runtime.

**Comment by Nikola25** [comment]
Change the visibility of this constructor to 'protected'.
Location: Libraries/dotNetRDF.Web/Configuration/Server/BaseSparqlServerConfiguration.cs

**Comment by hareka777** [comment]
Fix: **Introduce a new readonly variable instead of reusing the parameter**
Reason: Safety reasons, because the new variable cannot be modified.
Location : Testing/unittest/Query/FullText/FullTextOptimiserTests.cs
Assignee: Réka
Reviewer: Nikola
Pull Request:

**Comment by Nikola25** [comment]
Either merge this branch with the identical one on line 134 or change one of the implementations.
Reason: Having two cases in the same switch statement or branches in the same if structure with the same implementation is at best duplicate code, and at worst a coding error. If the same logic is truly needed for both instances, then in an if structure they should be combined, or for a switch, one should fall through to the other.
Location: Libraries/dotNetRDF.Query.Spin/Model/BaseImpl/FunctionCallImpl.cs
Pull Request:

**Comment by hareka777** [comment]
We have fixed bugs from the categories what Codacy advised.
We decided not to change "Remove logging this statement" bugs, because the the application does not have user interface, and these logged informations help us in debugging and gives us informations about the state of the program. 
These logging codes are also help understanding the code, they can replace the comments in some cases.

**Comment by hareka777** [comment]
The Codacy dashboard is avalable at the following link:
https://app.codacy.com/project/hareka777/IET-BARN-iet-2019/dashboard

**Comment by Nikola25** [comment]
We're ready.
