### ISSUE TITLE
Measuring coverage and create tests (dotCover)

### ISSUE THREAD

**Issue by hareka777** [BME-MIT-IET/IET-BARN-iet-2019#24]
Measuring code coverage using dotCover in Visual Studio and creating some tests based on the code coverage results.

**Comment by hareka777** [comment]
dotCover results:
![dotCoverReport](https://user-images.githubusercontent.com/37445999/57983540-416c4680-7a53-11e9-97ac-47820cd34e64.PNG)

**Comment by deviladam** [comment]
Result for me:
![cove01](https://user-images.githubusercontent.com/37347567/57985633-fe1dd200-7a6a-11e9-9bbe-8d69efd590a3.PNG)

With pull request: #26 

![cove02](https://user-images.githubusercontent.com/37347567/57985641-29082600-7a6b-11e9-8622-36e4c18b943e.PNG)
(I do not show coverage for Testing here.)

**Comment by hareka777** [comment]
These are the hot sports:
![image](https://user-images.githubusercontent.com/37445999/57986600-2dd2d700-7a77-11e9-80e0-60a879bbdd00.png)

**Comment by hareka777** [comment]
Test: Adding to tge graph collection the same elements.
Class: Testing/unittest/Core/GraphCollectionTests.cs
Assignee: Réka
Reviewer: Ádám

**Comment by deviladam** [comment]
Tests: Testing VDS.RDF.PredicateComparer, VDS.RDF.ObjectComparer and VDS.RDF.SubjectComparer
Class: Testing/unittest/Core/TripleComparers.cs
Assignee: Ádám
Reviewer: Beatrix
Pull Request: #26

**Comment by Nikola25** [comment]
Tests: AreUrisEqualTest
Class: Testing/unittest/Core/EqualityHelperTest
Assignee: Nikola
Reviewer: Réka
![image](https://user-images.githubusercontent.com/29783869/57987680-126ec880-7a85-11e9-9260-9abb75b00c93.png)
Pull Request: #28

**Comment by Nikola25** [comment]
Tests: AreGraphLiteralsEqualTest
Class: Testing/unittest/Core/EqualityHelperTest
Assignee: Nikola
Reviewer: Réka
![image](https://user-images.githubusercontent.com/29783869/57987748-40a0d800-7a86-11e9-905f-f41035e34c90.png)
Pull Request: #29

**Comment by hareka777** [comment]
Final results:
![image](https://user-images.githubusercontent.com/37445999/57988344-68e00500-7a8d-11e9-8331-a2b338ed082d.png)
