### ISSUE TITLE
Creating unit tests using xUnit

### ISSUE THREAD

**Issue by hareka777** [BME-MIT-IET/IET-BARN-iet-2019#25]
Creating some unit tests, we use the xUnit NuGet package for that.

**Comment by hareka777** [comment]
First step is to install ReSharper to run the tests.

**Comment by hareka777** [comment]
I think we do not have enough tests in dotNetRdf/Core , i will create test classes to test this class.

**Comment by hareka777** [comment]
Test:
- checking if a graph match to null
- checking if the same graphs are considered subgraphs
Class: Testing/unittest/Core/SubGraphMatchingTest.cs
Assignee: Réka
Reviewer: Ádám
Pull Request: #22

**Comment by hareka777** [comment]
Test:TripleComparer Tests
1.comparing the triples with the same parameters
2.comparing the triples with different types and graphs
Class: Testing/unittest/Core/TripleComparerTest.cs
Assignee: Réka
Reviewer: Ádám
Pull Request: #23

**Comment by Nikola25** [comment]
Test: GraphCollectionRemoveTest
1.checking Verifies that you remove this graph from the collection if it is included.
2.checking Verifies that you remove this graph from the collection if it is not included.
Class: Testing/unittest/Core/GraphCollectionRemoveTest.cs
Assignee: Nikola
Reviewer: Réka
Pull Request: #27

**Comment by deviladam** [comment]
Test: GraphFactory class testing
Class: Testing/unittest/Core/GraphFactoryTest.cs
Assignee: Ádám
Reviewer: Réka
Pull Request: #31

**Comment by Bexii077** [comment]
Test: WrapperTripleStoreTests
Class: Testing/unittest/Core/WrapperTripleStoreTest.cs
Assignee: Beatrix
Reviewer: Nikola
Pull Request: #30

**Comment by Bexii077** [comment]
Test: BaseVariableNodeTests
Class: Testing/unittest/Core/BaseVariableNodeTests.cs
Assignee: Beatrix
Reviewer: 
Pull Request:
